### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by task-jp** [Ar-Ray-code/rpi-bullseye-ros2-book#1]
https://zenn.dev/array/books/5efdb438cf8be3/viewer/b6b019#raspberrypi-os
の

> ラズベリー杯財団公式ページ

は

> ラズベリーパイ財団公式ページ

の誤記だと思います。

**Comment by Ar-Ray-code** [comment]
お読みいただき、ありがとうございます。
ご指摘の箇所の確認・修正を行いました。

他にも気になる点があれば、お気軽にお問い合わせください🙇
